my_website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from employee.views import dashboard as index

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', index, name='index'),
    
    path('employee/', include('employee.urls')),
    path('employee/', include('django.contrib.auth.urls')),
    path('', include('project.urls', namespace='project')),
    path('', include('task.urls')),
    path('', include('invitation.urls', namespace='invitation')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views


app_name = 'project'
urlpatterns = [
    path('projects/', views.projects, name='projects'),
    path('project/<int:project_id>/', views.project, name='project'),
    path('create-project/', views.createProject, name='create-project'),
    path('update-project/<int:project_id>', views.updateProject, name='update-project'),
    path('delete-project/<int:project_id>', views.deleteProject, name='delete-project'),
    path('project/<int:id>/participants/', views.get_participants, name='get-participants'),
]

task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('project/<int:project_id>/tasks/', views.tasks, name='tasks'),
    path('update-task/<int:id>', views.update_task, name='update-task'),
    path('project/<int:project_id>/create-task/', views.create_task, name='create-task'),
    path('your-tasks', views.your_task, name='your-tasks'),
    path('turn-in-task', views.turn_in_task, name='turn-in-task'),
    path('undone-task', views.undone_task, name='undone-task'),
    
]

task/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=300)
    due_date = models.DateTimeField()
    description = models.TextField()
    completed = models.BooleanField(default=False)
    
    assigned_to = models.ForeignKey('employee.User', on_delete=models.CASCADE, related_name='tasks')
    belongs_to = models.ForeignKey('project.Project', on_delete=models.CASCADE, related_name='tasks')

    def __str__(self):
        return self.name

task/forms.py
from django import forms
from .models import Task
from datetime import datetime

class TaskForm(forms.ModelForm):
    due_date_date = forms.DateField(widget=forms.DateInput())
    due_date_time = forms.TimeField(widget=forms.TimeInput())
    
    class Meta:
        model = Task
        fields = ['name', 'description', 'completed', 'assigned_to']

    def clean(self):
        cleaned_data = super().clean()
        date = cleaned_data.get('due_date_date')
        time = cleaned_data.get('due_date_time')

        if not date:
            raise forms.ValidationError("The date field is required")
        
        if not time:
            raise forms.ValidationError("The time field is required")
        
        # Combine date and time into a single datetime object
        cleaned_data['due_date'] = datetime.combine(date, time)
        return cleaned_data
    
    def save(self, commit=True):
        instance = super().save(commit=False)
        
        # manually set the due_date field
        instance.due_date = self.cleaned_data.get('due_date')

        if commit:
            instance.save()
        return instance

task/views.py
from django.shortcuts import redirect, render
from django.urls import reverse

from decorators.custom_decorator import identify_participant_of_project, identify_project_owner, required_project_owner
from project.models import Project
from task.forms import TaskForm
from .models import Task

from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

from django.contrib import messages

def filter_task(request, tasks, task_range='all', task_status='all'):
    if task_range == 'mine':
        tasks = tasks.filter(assigned_to=request.user)
    else:
        tasks = tasks.all()
    
    tasks = filter_tasks_by_status(tasks, task_status)
    
    return tasks

def filter_tasks_by_status(tasks, task_status='all'):
    if task_status == 'completed':
        tasks = tasks.filter(completed=True)
    elif task_status == 'in progress':
        tasks = tasks.filter(completed=False)
    
    return tasks

@login_required(login_url='/employee/sign_in')
@identify_project_owner
@identify_participant_of_project
def tasks(request, project_id):
    project = Project.objects.get(id=project_id)
    
    if not request.user.is_participant:
        context = { 
            'project': project, 
            'actived_page': 'tasks',
        }
        return render(request, 'task/task-denied-access.html', context)
    
    # User is participant of the project, so display the tasks
    task_range = request.GET.get('task_range', 'all')
    task_status = request.GET.get('task_status', 'all')
    
    tasks = filter_task(request, project.tasks, task_range, task_status)
    
    context = { 
        'project': project, 
        'tasks': tasks,
        'actived_page': 'tasks',
        'task_range': task_range,
        'task_status': task_status,
    }
    return render(request, 'task/page-task.html', context)

@login_required(login_url='/employee/sign_in')
def your_task(request):
    project_id = request.GET.get('project_id')
    
    if project_id is None:
        # Display the overview tasks of all participated_projects
        participated_projects = request.user.participated_projects.all()
        
        context = {
            'title': 'Tasks',
            'participated_projects': participated_projects,
            'actived_view': 'projects',
            'page_name': 'Your Task',
        }
        
        return render(request, 'task/your-tasks.html', context)
    
    # Display the tasks of a specific project
    project = Project.objects.get(id=project_id)
    your_tasks = Task.objects.filter(belongs_to=project, assigned_to=request.user)
    
    completed_tasks = filter_tasks_by_status(your_tasks, 'completed')
    num_completed_tasks = completed_tasks.count()
    
    in_progress_tasks = filter_tasks_by_status(your_tasks, 'in progress')
    num_in_progress_tasks = in_progress_tasks.count()
    
    context = {
        'title': 'Tasks',
        'completed_tasks': completed_tasks,
        'num_completed_tasks': num_completed_tasks,
        
        'in_progress_tasks': in_progress_tasks,
        'num_in_progress_tasks': num_in_progress_tasks,
        
        'project_name': project.name,
        'project_id': project_id,
        
        'actived_view': 'tasks',


    }
    return render(request, 'task/your-tasks.html', context)

@require_POST
@identify_project_owner
@required_project_owner
@login_required(login_url='/employee/sign_in')
def create_task(request, project_id):
    form = TaskForm(request.POST)
    
    if form.is_valid():
        task = form.save(commit=False)
        task.belongs_to = Project.objects.get(id=project_id)
        task.save()
        messages.success(request, 'Created new Task successfully!')
        return redirect('tasks', task.belongs_to.id)
        
    messages.error(request, 'Failed to create new Task!')
    return redirect('tasks', task.belongs_to.id)

@require_POST
@login_required(login_url='/employee/sign_in')
def update_task(request, id):
    task = Task.objects.get(id=id)
    
    if task.assigned_to != request.user:
        messages.error(request, 'You do not have permission to update this Task!')
        return redirect('tasks', task.belongs_to.id)
    
    form = TaskForm(request.POST, instance=task)
    
    if form.is_valid():
        form.save()
        messages.success(request, 'Task updated successfully!')
        return redirect('tasks', task.belongs_to.id)
        
    messages.error(request, 'Failed to update this Task!')
    return redirect('tasks', task.belongs_to.id)

@require_POST
@login_required(login_url='/employee/sign_in')
def turn_in_task(request):
    task_id = request.POST.get('task_id')
    
    task_obj = Task.objects.get(id=task_id)
    task_obj.completed = True
    task_obj.save()
    
    project_id = task_obj.belongs_to.id 
    
    url = reverse('your-tasks') + f'?project_id={project_id}'
    return redirect(url)

@require_POST
@login_required(login_url='/employee/sign_in')
def undone_task(request):
    task_id = request.POST.get('task_id')
    
    task_obj = Task.objects.get(id=task_id)
    task_obj.completed = False
    task_obj.save()
    
    project_id = task_obj.belongs_to.id 
    
    url = reverse('your-tasks') + f'?project_id={project_id}'
    return redirect(url)
    
    
    

task/templates/task/create-task-modal.html
<!-- Model creating new Task -->
<div class="modal fade bd-example-modal-lg" role="dialog" aria-modal="true" id="new-task-modal">
    <div class="modal-dialog  modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header d-block text-center pb-3 border-bttom">
                <h3 class="modal-title" id="exampleModalCenterTitle">New Task</h3>
            </div>
            <div class="modal-body">
                <form class="row" method="post" action="{% url 'create-task' project.id %}">
                    {% csrf_token %}
                    <div class="col-lg-12">
                        <div class="form-group mb-3">
                            <label for="id_name" class="h5">Task Name</label>
                            <input type="text" class="form-control" id="id_name" name="name" required 
                                placeholder="Enter task name">
                            <a href="#" class="task-edit text-body"><i class="ri-edit-box-line"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group mb-3">
                            <label for="id_assigned_to" class="h5">Assigned to</label>
                            <select id="id_assigned_to" name="assigned_to" class="selectpicker form-control" data-style="py-0" required>
                                <option value selected>Memebers</option>
                                
                                {% with participated_employee=project.participants.all %}
                                    {% for employee in participated_employee %}
                                        <option value="{{employee.username}}">
                                            {{employee}}
                                        </option>
                                    {% endfor %}
                                {% endwith %}
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group mb-3">
                            <label for="id_due_date_date" class="h5">Due Date</label>
                            <input name="due_date_date" type="date" class="form-control"
                                id="id_due_date_date" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group mb-3">
                            <label for="id_due_date_time" class="h5">Due Time</label>
                            <input name="due_date_time" type="time" class="form-control"
                                id="id_due_date_time" required>
                        </div>
                    </div>
                    <!-- <div class="col-lg-4">
                        <div class="form-group mb-3">
                            <label for="exampleInputText2" class="h5">Category</label>
                            <select name="type" class="selectpicker form-control" data-style="py-0">
                                <option>Design</option>
                                <option>Android</option>
                                <option>IOS</option>
                                <option>Ui/Ux Design</option>
                                <option>Development</option>
                            </select>
                        </div>
                    </div> -->
                    <div class="col-lg-12">
                        <div class="form-group mb-3">
                            <label for="id_description" class="h5">Description</label>
                            <textarea name="description" class="form-control" id="id_description" rows="3" placeholder="Enter task's description" required></textarea>
                        </div>
                    </div>
                    <!-- <div class="col-lg-12">
                        <div class="form-group mb-3">
                            <label for="exampleInputText005" class="h5">Checklist</label>
                            <input type="text" class="form-control" id="exampleInputText005" placeholder="Add List">
                        </div>
                    </div> -->
                    <!-- <div class="col-lg-12">
                        <div class="form-group mb-0">
                            <label for="exampleInputText01" class="h5">Attachments</label>
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="inputGroupFile003">
                                <label class="custom-file-label" for="inputGroupFile003">Upload media</label>
                            </div>
                        </div>
                    </div> -->
                    <div class="col-lg-12">
                        <div class="d-flex flex-wrap align-items-ceter justify-content-end">
                            <button type="submit" class="btn btn-primary mr-3 px-3">Save</button>
                            <div class="btn bg-danger-light" data-dismiss="modal">Cancel</div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

task/templates/task/task-denied-access.html
{% extends 'project-layout.html' %}

{% load static %}

{% block content_of_project_layout %}
<div class="col-lg-12 p-0">
    <div class="card">
        <div class="card-body p-5">
           <div class="h4 mb-3" style="text-align: center;">Only participants can view the tasks of this project!</div>
           <img src="{% static 'images/error/02.png'%}" class="img-fluid">
        </div>
    </div>
</div>
{% endblock content_of_project_layout %}

task/templates/task/your-tasks.html
{% extends 'base.html' %}

{% load task_progress_on_project %}
{% load task_progress_class %}

{% block css %}
<style>
    .table.tble-min-width td {
        min-width: 200px;
    }

    .table.tble-min-width tr td:first-child {
        min-width: 300px;
    }
    .table.tble-min-width tr td:last-child {
        min-width: 100px;
    }
</style>
{% endblock css %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-wrap align-items-center justify-content-between breadcrumb-content">
                        <div class="d-flex">
                            <h5>Project <i class="las la-clipboard-list mr-3"></i></h5>
                            <span>{% if project_name %} {{project_name}} {% else %} Select a following project to view your tasks {% endif %}</span>
                        </div>
                        
                        <div class="d-flex flex-wrap align-items-center justify-content-between">
                            <!-- <div class="dropdown status-dropdown mr-3">
                                <div class="dropdown-toggle" id="dropdownMenuButton03" data-toggle="dropdown">
                                    <div class="btn bg-body"><span class="h6">Status :</span> In Progress<i
                                            class="ri-arrow-down-s-line ml-2 mr-0"></i></div>
                                </div>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton03">
                                    <a class="dropdown-item" href="#"><i class="ri-mic-line mr-2"></i>In
                                        Progress</a>
                                    <a class="dropdown-item" href="#"><i
                                            class="ri-attachment-line mr-2"></i>Priority</a>
                                    <a class="dropdown-item" href="#"><i class="ri-file-copy-line mr-2"></i>Category</a>
                                </div>
                            </div> -->
                            <div class="list-grid-toggle d-flex align-items-center mr-3">
                                <!-- Grid option button -->
                                <div data-toggle-extra="tab" data-target-extra="#grid" class="{% if actived_view == 'tasks' %} active {% endif %}">
                                    <div class="grid-icon mr-3">
                                        <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg"
                                            viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                            stroke-linecap="round" stroke-linejoin="round">
                                            <rect x="3" y="3" width="7" height="7"></rect>
                                            <rect x="14" y="3" width="7" height="7"></rect>
                                            <rect x="14" y="14" width="7" height="7"></rect>
                                            <rect x="3" y="14" width="7" height="7"></rect>
                                        </svg>
                                    </div>
                                </div>

                                <!-- List option button -->
                                <a href="{% url 'your-tasks' %}" style="color: inherit;" data-toggle-extra="tab" data-target-extra="#list" class="{% if actived_view == 'projects' %} active {% endif %}">
                                    <div class="grid-icon">
                                        <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg"
                                            viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                            stroke-linecap="round" stroke-linejoin="round">
                                            <line x1="21" y1="10" x2="3" y2="10"></line>
                                            <line x1="21" y1="6" x2="3" y2="6"></line>
                                            <line x1="21" y1="14" x2="3" y2="14"></line>
                                            <line x1="21" y1="18" x2="3" y2="18"></line>
                                        </svg>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if actived_view == 'tasks' %}
    <!-- View grid option -->
    <div id="grid" class="item-content animate__animated animate__fadeIn active" data-toggle-extra="tab-content">
        <div class="row">
            <!-- In progress tasks column -->
            <div class="col-lg-6">
                <div class="card-transparent mb-0 desk-info">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex align-items-center justify-content-between">
                                            <h5>In Progress ( {{num_in_progress_tasks}} Task{{ num_in_progress_tasks|pluralize }} )</h5>
                                            <div class="dropdown">
                                                <span class="dropdown-toggle py-2" id="dropdownMenuButton05"
                                                    data-toggle="dropdown">
                                                    <i class="ri-more-fill"></i>
                                                </span>
                                                <div class="dropdown-menu dropdown-menu-right"
                                                    aria-labelledby="dropdownMenuButton05">
                                                    <a class="dropdown-item" href="#"><i
                                                            class="ri-file-copy-2-line mr-2"></i>Duplicate</a>
                                                    <a class="dropdown-item" href="#"><i
                                                            class="ri-edit-2-line mr-2"></i>Rename</a>
                                                    <a class="dropdown-item" href="#"><i
                                                            class="ri-delete-bin-5-line mr-2"></i>Delete</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                {% for task in in_progress_tasks %}
                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex justify-content-between align-items-start">
                                            <h5 class="mb-3">{{task.name}}</h5>
                                            <button class="btn bg-primary-light btn-sm" type="submit" form="form-turn-in-{{task.id}}">
                                                Turn in
                                            </button>
                                        </div>
                                        <form method="post" action="{% url 'turn-in-task'%}" id="form-turn-in-{{task.id}}">
                                            {% csrf_token %}
                                            <input type="hidden" name="task_id" value="{{task.id}}">
                                        </form>
                                        <p class="mb-3"><i class="las la-calendar-check mr-2"></i>{{task.due_date}}</p>
                                        <p class="mb-3">{{task.description}}</p>

                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- In completed tasks column -->
            <div class="col-lg-6">
                <div class="card-transparent mb-0 desk-info">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex align-items-center justify-content-between">
                                            <h5>Completed ( {{num_completed_tasks}} Task{{num_completed_tasks|pluralize}} )</h5>
                                            <div class="dropdown">
                                                <span class="dropdown-toggle py-2" id="dropdownMenuButton06"
                                                    data-toggle="dropdown">
                                                    <i class="ri-more-fill"></i>
                                                </span>
                                                <div class="dropdown-menu dropdown-menu-right"
                                                    aria-labelledby="dropdownMenuButton06">
                                                    <a class="dropdown-item" href="#"><i
                                                            class="ri-file-copy-2-line mr-2"></i>Duplicate</a>
                                                    <a class="dropdown-item" href="#"><i
                                                            class="ri-edit-2-line mr-2"></i>Rename</a>
                                                    <a class="dropdown-item" href="#"><i
                                                            class="ri-delete-bin-5-line mr-2"></i>Delete</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-12">
                                {% for task in completed_tasks %}
                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex justify-content-between align-items-start">
                                            <h5 class="mb-3">{{task.name}}</h5>
                                            <button class="btn bg-danger-light btn-sm" type="submit" form="form-undone-{{task.id}}">
                                                Undone
                                            </button>
                                        </div>
                                        <form method="post" action="{% url 'undone-task' %}" id="form-undone-{{task.id}}">
                                            {% csrf_token %}
                                            <input type="hidden" name="task_id" value="{{task.id}}">
                                        </form>

                                        <p class="mb-3"><i class="las la-calendar-check mr-2"></i>{{task.due_date}}</p>
                                        <p class="mb-3">{{task.description}}</p>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <!-- View list option -->
    <div id="list" class="item-content animate__animated animate__fadeIn active" data-toggle-extra="tab-content">
        <div class="table-responsive rounded bg-white mb-4">
            <table class="table mb-0 table-borderless tbl-server-info tble-min-width">
                <tbody>
                    {% for project in participated_projects %}
                    
                    <tr>
                        <td><a href="{% url 'project:project' project.id %}" style="color: inherit;">{{project.name}}</a></td>
                        <td class="w-25">
                            {% with task_progress=project|task_progress_percentage:request.user %}
                            <div class="iq-progress-bar bg-{{task_progress|task_progress_class}}-light">
                                <span class="bg-{{task_progress|task_progress_class}} iq-progress progress-1" data-percent="{{task_progress}}"></span>
                            </div>
                            {% endwith %}
                        </td>
                        <td>
                            <p class="mb-0"><i class="las la-tasks mr-2"></i>{{project|task_progress_text:request.user}}</p>
                        </td>
                        <td>
                            <p class="mb-0"><i class="las la-calendar-check mr-2"></i>{{project.due_date|date}}</p>
                        </td>
                        <!-- <td>
                            <a href="#" class="btn bg-secondary-light">Design</a>
                        </td> -->
                        <td>
                            <a href="{% url 'your-tasks' %}?project_id={{project.id}}">View</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
</div>

{% endblock content %}