my_website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from employee.views import dashboard as index

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', index, name='index'),
    
    path('employee/', include('employee.urls')),
    path('employee/', include('django.contrib.auth.urls')),
    path('', include('project.urls', namespace='project')),
    path('', include('task.urls')),
    path('', include('invitation.urls', namespace='invitation')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views


app_name = 'project'
urlpatterns = [
    path('projects/', views.projects, name='projects'),
    path('project/<int:project_id>/', views.project, name='project'),
    path('create-project/', views.createProject, name='create-project'),
    path('update-project/<int:project_id>', views.updateProject, name='update-project'),
    path('delete-project/<int:project_id>', views.deleteProject, name='delete-project'),
    path('project/<int:id>/participants/', views.get_participants, name='get-participants'),
]

task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('project/<int:project_id>/tasks/', views.tasks, name='tasks'),
    path('update-task/<int:id>', views.update_task, name='update-task'),
    path('project/<int:project_id>/create-task/', views.create_task, name='create-task'),
    path('your-tasks', views.your_task, name='your-tasks'),
    path('turn-in-task', views.turn_in_task, name='turn-in-task'),
    path('undone-task', views.undone_task, name='undone-task'),
    
]

project/models.py
from django.db import models
# from employee.models import User

class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey('employee.User', on_delete=models.CASCADE, related_name='owned_projects')
    due_date = models.DateTimeField()
    created_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='project-images/', null=True, blank=True, default='project-images/default.jpg')
    
    def __str__(self):
        return self.name

project/forms.py
from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    due_date_0 = forms.DateField(
        widget=forms.DateInput(attrs={
            'class': 'form-control col-sm-8',
            'required': True,
            'type': 'date',
        })
    )
    due_date_1 = forms.TimeField(
        widget=forms.TimeInput(attrs={
            'class': 'form-control col-sm-4',
            'required': True,
            'type': 'time',
        })
    )
    
    due_date = forms.DateTimeField(required=False, widget=forms.HiddenInput())

    class Meta:
        model = Project
        fields = ['name', 'description', 'due_date', 'image']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Project Name',
                'required': True,
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
                'required': True,
            }),
        }

    # Set value for due_date_0 and due_date_1 fields if the instance is passed
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields['due_date_0'].initial = self.instance.due_date.date()
            self.fields['due_date_1'].initial = self.instance.due_date.time()
            
    def clean_due_date(self):
        print('clean_due_date()', 30*'---')
        
        due_date_0 = self.data.get('due_date_0')
        due_date_1 = self.data.get('due_date_1')

        if not due_date_0:
            raise forms.ValidationError("The date field is required")
        
        if not due_date_1:
            raise forms.ValidationError("The time field is required")
        
        due_date_value = ' '.join([due_date_0, due_date_1])
        print(due_date_value, type(due_date_value))
        
        return due_date_value
    
    # def clean(self):
    #     print('clean()', 30*'--')
        
    #     cleaned_data = super().clean()
    #     print(cleaned_data)
    #     print(30*'--')
    #     print(self.data)
    #     print(30*'--')
        
    #     due_date_0 = cleaned_data.get('due_date_0')
    #     due_date_1 = cleaned_data.get('due_date_1')
        
    #     print('due_date_0:', due_date_0)
    #     print('due_date_1:', due_date_1)

    #     if due_date_1 is None:
    #         raise forms.ValidationError("The date field is required")
        
    #     if due_date_0 is None:
    #         raise forms.ValidationError("The time field is required")
        
    #     cleaned_data['due_date'] = datetime.datetime.combine(due_date_0, due_date_1)
        
    #     print(cleaned_data['due_date'], type(cleaned_data['due_date']))
        
    #     return cleaned_data

project/views.py
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.core.paginator import Paginator

from .forms import ProjectForm
from .models import Project

from decorators.custom_decorator import identify_project_owner, required_project_owner
from django.contrib.auth.decorators import login_required

def store_form(request, form):
    request.session['form_data'] = form.data
    request.session['form_errors'] = form.errors

def get_stored_form_or_create_one(request, form_class):
    form = get_stored_form(request, form_class)
    
    if form is None:
        form = form_class()
        
    return form

def get_stored_form(request, form_class):
    form_data = request.session.pop('form_data', None)
    form_errors = request.session.pop('form_errors', None)

    if form_data is not None:
        form = form_class(form_data)
        form.is_valid()  # Populate form.errors
        # form.errors.update(form_errors)
        return form
    
    return None

@login_required(login_url='/employee/sign_in')
def projects(request):
    filter_by = request.GET.get('filter_by', 'all')
    if filter_by == 'participated':
        projects_list = request.user.participated_projects.all()
    elif filter_by == 'mine':
        projects_list = request.user.owned_projects.all()
    else:
        projects_list = Project.objects.all()
    
    # Continue filtering by search query
    search_query = request.GET.get('search', '')
    projects_list = projects_list.filter(name__icontains=search_query)
    
    paginator = Paginator(projects_list, 6)

    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    
    view_option = request.GET.get('view_option', 'grid')

    form = get_stored_form_or_create_one(request, ProjectForm)
    context = {
        'title': 'Projects',
        'page': page, 
        'form': form,
        'filter_by': filter_by,
        'search_query': search_query,
        'view_option': view_option,
        'page_name': 'Project'
    }    
    return render(request, 'project/page-project.html', context)

@login_required(login_url='/employee/sign_in')
@identify_project_owner
def project(request, project_id):
    project = Project.objects.get(id=project_id)
    form = get_stored_form(request, ProjectForm)
    if form is None:
        form = ProjectForm(instance=project)
    
    context = {
        'title': 'Projects',
        'project': project,
        'form': form,
        'actived_page': 'details'
    }
    return render(request, 'project/single-project.html', context)

@require_POST
@login_required(login_url='/employee/sign_in')
def createProject(request):
    form = ProjectForm(request.POST, request.FILES)
    
    if form.is_valid():
        project = form.save(commit=False)
        project.owner = request.user
        project.save()
        project.participants.add(request.user)
        messages.success(request, 'Created project successfully!')
        return redirect('project:projects')
    
    messages.error(request, 'Failed to create new project!')
    
    store_form(request, form)
    return redirect('project:projects')


@require_POST
@login_required(login_url='/employee/sign_in')
@identify_project_owner
@required_project_owner
def updateProject(request, project_id):
    project = Project.objects.get(id=project_id)
    form = ProjectForm(request.POST, request.FILES, instance=project)
    
    if form.is_valid():
        form.save()
        messages.success(request, 'Updated project successfully!')
        return redirect('project:project', project_id=project_id)
    
    messages.error(request, 'Failed to update this project!')
    store_form(request, form)
    return redirect('project:project', project_id=project_id)

@require_POST
@login_required(login_url='/employee/sign_in')
@identify_project_owner
@required_project_owner
def deleteProject(request, project_id):
    project = Project.objects.get(id=project_id)
    project_name = project.name
    
    project.delete()
    messages.success(request, 'Deleted project "%s" successfully!' % project_name)
    
    return redirect('project:projects')

# Get participants in the project that has id
@login_required(login_url='/employee/sign_in')
def get_participants(request, id):
    project = Project.objects.get(id=id)
    
    context = {
        'title': 'Projects',
        'project': project,
        'actived_page': 'participated employees'
    }
    
    return render(request, 'project/participated-employees.html', context)

project/templates/project/create-project-modal.html
<!-- Model creating new Project -->
<div class="modal fade" role="dialog" aria-modal="true" id="new-project-modal">
    <div class="modal-dialog  modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header d-block text-center pb-3 border-bttom">
                <h3 class="modal-title" id="exampleModalCenterTitle01">New Project</h3>
            </div>
            <div class="modal-body">
                <form id="form-create-project" class="" novalidate method="post" 
                        action="{% url 'project:create-project' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.due_date }}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group mb-3">
                                <label for="{{ form.name.id_for_label }}" class="h5">Project Name*</label>
                                {{ form.name }}
                    
                                {% if form.name.errors %}
                                    {{ form.name.errors }}
                                {% else %}
                                <div class="invalid-feedback">
                                    Project name is required
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group mb-3">
                                <label for="{{ form.description.id_for_label }}" class="h5">Description*</label>
                                {{ form.description }}
                                
                                {% if form.description.errors %}
                                    {{ form.description.errors }}
                                {% else %}
                                <div class="invalid-feedback">
                                    Description field is required
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group mb-3">
                                <label for="{{ form.due_date_0.id_for_label }}" class="h5">Due Dates*</label>
                                <div class="d-flex gap-2">
                                    {{ form.due_date_0 }}
                                    {{ form.due_date_1 }}
                                </div>
                                
                                {% if form.due_date.errors %}
                                    {{ form.due_date.errors }}
                                {% else %}
                                <div class="invalid-feedback col-12 ps-0" id="due-date-invalid-feeback">
                                    Due date is required
                                </div>
                                {% endif %}
                                
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group mb-3">
                                <label for="id_image" class="h5">Featured Image</label>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="id_image" name="image">
                                    <label class="custom-file-label" for="id_image">Upload media</label>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="d-flex flex-wrap align-items-ceter justify-content-end">
                                <button type="submit" class="btn btn-primary mr-3 px-3">Save</button>
                                <div class="btn bg-danger-light" data-dismiss="modal">Cancel</div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    date_input = document.getElementById('id_due_date_0');
    time_input = document.getElementById('id_due_date_1');

    due_date_feedback = document.getElementById('due-date-invalid-feeback');

    create_project_form = document.getElementById('form-create-project');

    date_input.addEventListener('input', function() {
        if (create_project_form.classList.contains('was-validated')) {
            resolveDueDateMessage();
        }
    });

    time_input.addEventListener('input', function() {
        if (create_project_form.classList.contains('was-validated')) {
            resolveDueDateMessage();
        }
    });

    create_project_form.addEventListener('submit', (e) => {
        if (!create_project_form.classList.contains('needs-validation')) {
            return;
        }

        if (create_project_form.checkValidity() === false) {
            e.preventDefault();
        }

        console.log('Create project form submit event triggered');
        resolveDueDateMessage();
    });

    function resolveDueDateMessage() {
        if (date_input.validity.valid && time_input.validity.valid) {
            console.log('valid');
            due_date_feedback.style.display = 'none';
        } else {
            console.log('invalid');
            due_date_feedback.style.display = 'block';
        }
    }

</script>

{% if form.errors %}
<script>
    // Auto open the modal if the form validation at server fails
    document.addEventListener('DOMContentLoaded', function() {
        openModalBtn = document.getElementById('open-create-project-modal');
        if (openModalBtn) {
            console.log('Auto opening modal');
            openModalBtn.click();
        }
    });
</script>
{% endif %}

project/templates/project/participated-employees.html
{% extends 'project-layout.html' %}

{% load static %}

{% block content_of_project_layout %}
{% include 'invitation/create-invitation-modal.html' %}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="d-flex flex-wrap align-items-center justify-content-between breadcrumb-content">
                    <h5>Participants</h5>
                    <div class="d-flex align-items-center">
                        <div class="pl-3 border-left btn-new">
                            <a href="#" class="btn btn-primary" data-target="#create-invitation-modal" data-toggle="modal">Invite
                            People</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="grid" class="item-content animate__animated animate__fadeIn active" data-toggle-extra="tab-content">
    <div class="row">
        {% for employee in project.participants.all %}
        <div class="col-lg-4 col-md-6">
            <div class="card-transparent card-block card-stretch card-height">
                <div class="card-body text-center p-0">
                    <div class="item">
                        <div class="odr-img">
                            <img src="{% if employee.avatar %}{{ employee.avatar.url }}{% else %}{% static 'media/avatars/default.jpg' %}{% endif %}" class="img-fluid rounded-circle avatar-90 m-auto"
                                alt="image">
                        </div>

                        <div class="odr-content rounded"
                            {% if employee == project.owner or employee == request.user %}
                                style="padding-top: 20px;"
                            {% endif %}
                            >
                            {% if employee == project.owner %}
                            <span class="badge badge-warning mb-3" >
                                Owner
                            </span>
                            {% elif employee == request.user %}
                            <span class="badge badge-secondary mb-3">
                                You
                            </span>
                            {% endif %}

                            <h4 class="mb-2">{{employee.name}}</h4>
                            <p class="mb-3">{{employee.email}}</p>

                            <ul class="list-unstyled mb-3">
                                <li class="bg-secondary-light rounded-circle iq-card-icon-small mr-4"><i
                                        class="ri-mail-open-line m-0"></i></li>
                                <li class="bg-primary-light rounded-circle iq-card-icon-small mr-4"><i
                                        class="ri-chat-3-line m-0"></i></li>
                                <li class="bg-success-light rounded-circle iq-card-icon-small"><i
                                        class="ri-phone-line m-0"></i></li>
                            </ul>

                            <div class="pt-3 border-top">
                                <a href="#" class="btn btn-primary">Message</a>
                                <a href="#" class="btn btn-danger px-4">Fire</a>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content_of_project_layout %}

project/templates/project/single-project.html
{% extends 'project-layout.html' %}
{% load static %}
{% load file_name %}

{% block content_of_project_layout %}

<div class="card p-4">
    <form class="" novalidate method="post" action="{% url 'project:update-project' project.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.due_date }}
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group mb-3">
                    <label for="{{ form.name.id_for_label }}" class="h5">Project Name</label>
                    {{ form.name }}
        
                    {% if form.name.errors %}
                        {{ form.name.errors }}
                    {% else %}
                    <div class="invalid-feedback">
                        Project name is required
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group mb-3">
                    <label for="{{ form.description.id_for_label }}" class="h5">Description</label>
                    {{ form.description }}
                    
                    {% if form.description.errors %}
                        {{ form.description.errors }}
                    {% else %}
                    <div class="invalid-feedback">
                        Description field is required
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group mb-3">
                    <label for="{{ form.due_date_0.id_for_label }}" class="h5">Due Dates</label>
                    <div class="d-flex gap-2">
                        {{ form.due_date_0 }}
                        {{ form.due_date_1 }}
                    </div>
                    
                    {% if form.due_date.errors %}
                        {{ form.due_date.errors }}
                    {% else %}
                    <div class="invalid-feedback col-12 ps-0" id="due-date-invalid-feeback">
                        Due date is required
                    </div>
                    {% endif %}
                    
                </div>
            </div>

            {% if request.user.is_project_owner %}
            <div class="col-lg-12">
                <div class="form-group mb-3">
                    <label for="id_image" class="h5">Featured Image</label>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="id_image" name="image">
                        <label class="custom-file-label" for="id_image">{{project.image.name|filename}}</label>
                    </div>
                </div>
            </div>
            <div class="form-group d-flex justify-content-end">
                <button type="submit" class="btn btn-info mt-2 py-1 px-5 me-3">
                    <i class="fas fa-save"></i>
                </button>
                <button type="button" class="btn btn-danger mt-2 py-1 px-5 me-3" data-toggle="modal" data-target="#confirm-delete-modal">
                    <i class="fas fa-trash"></i>
                </button>
            </div>
            {% endif %}

        </div>
    </form>
</div>

{% if request.user.is_project_owner %}
<div class="modal fade" id="confirm-delete-modal" tabindex="-1" aria-labelledby="exampleModalLabel" style="display: none;"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="mb-2">Do you want to delete this project?</p>
                <p>(This action cannot be undone)</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="confirm-delete-btn">Confirm</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<form id="delete-project-form" method="post" action="{% url 'project:delete-project' project.id %}">
    {% csrf_token %}
</form>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const confirmDeleteBtn = document.getElementById('confirm-delete-btn');
        confirmDeleteBtn.addEventListener('click', () => {
            document.getElementById('delete-project-form').submit();
        });
    });
</script>
{% endif %}

{% endblock content_of_project_layout %}

project/templates/project/temp.html
<div class="row">
    <div class="col-lg-12">
        <div class="form-group mb-3">
            <label for="name" class="h5">Project Name*</label>
            <input type="text" class="form-control {% if errors.name %} {{errors.name}} {% endif %}" id="name" name="name"
                placeholder="Project Name" required>
            <div class="invalid-feedback">
                Project name is required
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="form-group mb-3">
            <label for="description" class="h5">Description</label>
            <textarea class="form-control" id="description" name="description" rows="3" required>{{project.description}}</textarea>
            <div class="invalid-feedback">
                Description field is required
            </div>
        </div>
    </div>
    <!-- <div class="col-lg-6">
        <div class="form-group mb-3">
            <label for="exampleInputText2" class="h5">Categories *</label>
            <select name="type" class="selectpicker form-control" data-style="py-0">
                <option>Category</option>
                <option>Android</option>
                <option>IOS</option>
                <option>Ui/Ux Design</option>
                <option>Development</option>
            </select>
        </div>
    </div> -->
    <div class="col-lg-12">
        <div class="form-group mb-3">
            <label for="due_date_0" class="h5">Due Dates*</label>
            <div class="d-flex gap-2">
                <input type="date" class="form-control col-sm-8" id="due_date_0" name="due_date_0" required>
                <input type="time" class="form-control col-sm-4" id="due_date_1" name="due_date_1" required>
            </div>
            <div class="invalid-feedback col-12 ps-0" id="due-date-invalid-feeback">
                Due date is required
            </div>
            
        </div>
    </div>
    <!-- <div class="col-lg-12">
        <div class="form-group mb-3">
            <label for="exampleInputText07" class="h5">Assign Members</label>
            <input type="text" class="form-control" id="exampleInputText07">
        </div>
    </div> -->
    <div class="col-lg-12">
        <div class="d-flex flex-wrap align-items-ceter justify-content-center mt-2">
            <button class="btn btn-primary mr-3" type="submit">Save</button>
            <div class="btn btn-primary" data-dismiss="modal">Cancel</div>
        </div>
    </div>
</div>