invitation/urls.py
from django.urls import path
from invitation import views


app_name = 'invitation'
urlpatterns = [
    path('send_invitation', views.send_invitation, name='send_invitation'),
    path('receive_invitation', views.receive_invitation, name='receive_invitation'),
    path('accept_invitation/<int:invitation_id>/', views.accept_invitation, name='accept_invitation'),
]

my_website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from employee.views import dashboard as index

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', index, name='index'),
    
    path('employee/', include('employee.urls')),
    path('employee/', include('django.contrib.auth.urls')),
    path('', include('project.urls', namespace='project')),
    path('', include('task.urls')),
    path('', include('invitation.urls', namespace='invitation')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('project/<int:project_id>/tasks/', views.tasks, name='tasks'),
    path('update-task/<int:id>', views.update_task, name='update-task'),
    path('project/<int:project_id>/create-task/', views.create_task, name='create-task'),
    path('your-tasks', views.your_task, name='your-tasks'),
    path('turn-in-task', views.turn_in_task, name='turn-in-task'),
    path('undone-task', views.undone_task, name='undone-task'),
    
]

invitation/models.py
from django.db import models


# Create your models here.
class Invitation(models.Model):
    project = models.ForeignKey('project.Project', on_delete=models.CASCADE)
    invited_by = models.ForeignKey('employee.User', on_delete=models.CASCADE, related_name='sent_invitations')
    invited_user = models.ForeignKey('employee.User', on_delete=models.CASCADE, related_name='received_invitations')
    message = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f'Invitation from {self.invited_by.name} to {self.invited_user.name} for project {self.project.name}'

invitation/forms.py
from django import forms
from .models import Invitation


class InvitationForm(forms.ModelForm):
    class Meta:
        model = Invitation
        fields = ['message']

invitation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages  # Add this import
from .models import Invitation
from .forms import InvitationForm
from project.models import Project
from employee.models import User
from django.utils import timezone

@login_required
def send_invitation(request):
    project_id = request.POST['project_id']
    project = Project.objects.get(id=project_id)
    
    if request.method == 'POST':
        form = InvitationForm(request.POST)
        if form.is_valid():
            # project_name = request.POST['project_name']
            # project = get_object_or_404(Project, name=project_name)

            invited_user_name = request.POST['invited_user']
            invited_user = get_object_or_404(User, username=invited_user_name)

            message = request.POST['message']

            invitation = form.save(commit=False)
            invitation.project = project
            invitation.invited_user = invited_user
            invitation.message = message
            invitation.invited_by = request.user
            invitation.timestamp = timezone.datetime.now()
            invitation.save()
            
            messages.success(request, 'Invitation sent successfully!')
            # Optionally, send notification to the invited user here
            return redirect('project:get-participants', id=project.id)

    return redirect('project:get-participants', id=project.id)


@login_required
def receive_invitation(request):
    invitations = Invitation.objects.filter(invited_user=request.user)
    return render(request, 'base.html', {'invitations': invitations})


@login_required
def accept_invitation(request, invitation_id):
    invitation = get_object_or_404(Invitation, id=invitation_id, invited_user=request.user)
    if request.method == 'POST':
        invitation.accepted = True
        invitation.delete()
        # Optionally, you can add the user to the project participants here
        project = invitation.project
        project.participants.add(request.user)
        project.save()
        return redirect('project:get-participants', id=project.id)

invitation/templates/invitation/create-invitation-modal.html
<div class="modal fade bd-example-modal-lg" role="dialog" aria-modal="true" id="create-invitation-modal">
    <div class="modal-dialog  modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header d-block text-center pb-3 border-bttom">
                <h3 class="modal-title" id="">New Invitation</h3>
            </div>
            <div class="modal-body">
                <form id="invitation-form" method="POST" action="{% url 'invitation:send_invitation' %}">
                    {% csrf_token %}
                    <input type="hidden" name="project_id" value="{{ project.id }}">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group mb-3">
                                <label for="exampleInputText2" class="h5">Send Invitation To</label>
                                <input type="text" class="form-control" id="invited_user" name="invited_user"
                                       placeholder="Employee's username">
                                {% if form.invited_user.errors %}
                                <p class="error">{{ form.invited_user.errors }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <!-- <div class="col-lg-6">
                            <div class="form-group mb-3">
                                <label for="exampleInputText2" class="h5">Project</label>
                                <input type="text" class="form-control" id="project_name" name="project_name"
                                       placeholder="Project's name">
                                {% if form.project.errors %}
                                <p class="error">{{ form.project.errors }}</p>
                                {% endif %}
                            </div>
                        </div> -->
                        <div class="col-lg-12">
                            <div class="form-group mb-3">
                                <label for="exampleInputText04" class="h5">Message</label>
                                <input type="text" class="form-control" id="message" name="message"
                                       placeholder="Message...">
                                {% if form.message.errors %}
                                <p class="error">{{ form.message.errors }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="d-flex flex-wrap align-items-ceter justify-content-center mt-2">
                                <button type="submit" class="btn btn-primary mr-3">Send</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>