my_website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from employee.views import dashboard as index

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', index, name='index'),
    
    path('employee/', include('employee.urls')),
    path('employee/', include('django.contrib.auth.urls')),
    path('', include('project.urls', namespace='project')),
    path('', include('task.urls')),
    path('', include('invitation.urls', namespace='invitation')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views


app_name = 'project'
urlpatterns = [
    path('projects/', views.projects, name='projects'),
    path('project/<int:project_id>/', views.project, name='project'),
    path('create-project/', views.createProject, name='create-project'),
    path('update-project/<int:project_id>', views.updateProject, name='update-project'),
    path('delete-project/<int:project_id>', views.deleteProject, name='delete-project'),
    path('project/<int:id>/participants/', views.get_participants, name='get-participants'),
]

task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('project/<int:project_id>/tasks/', views.tasks, name='tasks'),
    path('update-task/<int:id>', views.update_task, name='update-task'),
    path('project/<int:project_id>/create-task/', views.create_task, name='create-task'),
    path('your-tasks', views.your_task, name='your-tasks'),
    path('turn-in-task', views.turn_in_task, name='turn-in-task'),
    path('undone-task', views.undone_task, name='undone-task'),
    
]

templates/alert-message.html
{% if messages %}
<div class="col-12 px-0">
    {% for message in messages %}
        {% if message.tags == 'success'%}
        <div class="alert alert-success flex-column pb-0" role="alert">
            <div class="iq-alert-text" style="padding-bottom: 7px;">{{message}}</div>
            <!-- <div class="progress" style="height: 4px;">
                <div class="progress-bar progress-bar-striped progress-bar-animated" 
                    role="progressbar" style="width: 0%; background-color: #605C8D;" aria-valuenow="0" aria-valuemin="0" 
                    aria-valuemax="100"></div>
            </div> -->
        </div>
        
        {% elif message.tags == 'error' %}
        <div class="alert alert-danger" role="alert">
            <div class="iq-alert-text">{{message}}</div>
        </div>
        {% else %}
        <div class="alert alert-warning" role="alert">
            <div class="iq-alert-text">{{message}}</div>
        </div>
        {% endif %}
    {% endfor %}
</div>


{% endif %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ page_name }}</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
    <link rel="stylesheet" href="{% static 'css/backend-plugin.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/backend.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/remixicon/fonts/remixicon.css' %}">

    <link rel="stylesheet" href="{% static 'vendor/tui-calendar/tui-calendar/dist/tui-calendar.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/tui-calendar/tui-date-picker/dist/tui-date-picker.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/tui-calendar/tui-time-picker/dist/tui-time-picker.css' %}">

    <!-- Custom css file -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    
    {% block css %}
    {% endblock css %}
</head>

<body class="  ">

    <!-- Wrapper Start -->
    <div class="wrapper">
        {% include 'navbar.html' %}

        <div class="content-page">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
    <!-- Wrapper End-->

    <!-- Modal list start -->
    
    {% include 'modal.html' %}

    {% include 'footer.html' %}


    {% block script %}
    {% endblock script %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static 'js/backend-bundle.min.js' %}"></script>
    <script src="{% static 'js/table-treeview.js' %}"></script>
    <script src="{% static 'js/customizer.js' %}"></script>
    <script async src="{% static 'js/chart-custom.js' %}"></script>
    <script async src="{% static 'js/slider.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'vendor/moment.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static 'js/auto-dispossing-alert.js' %}"></script>

</body>

</html>

templates/base2.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Webkit | Responsive Bootstrap 4 Admin Dashboard Template</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
    <link rel="stylesheet" href="{% static 'css/backend-plugin.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/backend.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/remixicon/fonts/remixicon.css' %}">

    <link rel="stylesheet" href="{% static 'vendor/tui-calendar/tui-calendar/dist/tui-calendar.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/tui-calendar/tui-date-picker/dist/tui-date-picker.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/tui-calendar/tui-time-picker/dist/tui-time-picker.css' %}">
</head>

<body class="  ">
    <!-- loader Start -->
    <!-- <div id="loading">
        <div id="loading-center">
        </div>
    </div> -->
    <!-- loader END -->
    
    <!-- Wrapper Start -->
    <div class="wrapper">
        {% include 'navbar.html' %}

        <div class="content-page">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
    <!-- Wrapper End-->

    <!-- Modal list start -->
    
    {% include 'modal.html' %}

    {% include 'footer.html' %}
    <!-- Backend Bundle JavaScript -->
    <script src="{% static 'js/backend-bundle.min.js' %}"></script>

    <!-- Table Treeview JavaScript -->
    <script src="{% static 'js/table-treeview.js' %}"></script>

    <!-- Chart Custom JavaScript -->
    <script src="{% static 'js/customizer.js' %}"></script>

    <!-- Chart Custom JavaScript -->
    <script async src="{% static 'js/chart-custom.js' %}"></script>
    <!-- Chart Custom JavaScript -->
    <script async src="{% static 'js/slider.js' %}"></script>

    <!-- app JavaScript -->
    <script src="{% static 'js/app.js' %}"></script>

    <script src="{% static 'vendor/moment.min.js' %}"></script>
</body>

</html>

templates/footer.html
<footer class="iq-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item"><a href="#">Django Website</a></li>
                </ul>
            </div>
            <div class="col-lg-6 text-right">
                <span class="mr-1">
                    <script>document.write(new Date().getFullYear())</script>©
                </span> <a href="#" class="">Chello</a>
            </div>
        </div>
    </div>
</footer>

templates/invitation-modal.html
<div class="modal fade bd-example-modal-lg" role="dialog" aria-modal="true" id="create-invitation-modal">
    <div class="modal-dialog  modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header d-block text-center pb-3 border-bttom">
                <h3 class="modal-title" id="">New Invitation</h3>
            </div>
            <div class="modal-body">
                <form id="invitation-form" method="POST" action="{% url 'invitation/send_invitation' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group mb-3">
                                <label for="exampleInputText2" class="h5">Send Invitation To</label>
                                <input type="text" class="form-control" id="invited_user" name="invited_user"
                                       placeholder="Employee's name">
                                {% if form.invited_user.errors %}
                                <p class="error">{{ form.invited_user.errors }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group mb-3">
                                <label for="exampleInputText2" class="h5">Project</label>
                                <input type="text" class="form-control" id="project" name="project"
                                       placeholder="Project's name">
                                {% if form.project.errors %}
                                <p class="error">{{ form.project.errors }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group mb-3">
                                <label for="exampleInputText04" class="h5">Message</label>
                                <input type="text" class="form-control" id="message" name="message"
                                       placeholder="Message...">
                                {% if form.message.errors %}
                                <p class="error">{{ form.message.errors }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="d-flex flex-wrap align-items-ceter justify-content-center mt-2">
                                <div class="btn btn-primary mr-3" data-dismiss="modal">Send</div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/modal.html
<div class="modal fade bd-example-modal-lg" role="dialog" aria-modal="true" id="new-user-modal">
    <div class="modal-dialog  modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header d-block text-center pb-3 border-bttom">
                <h3 class="modal-title" id="exampleModalCenterTitle02">New User</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group mb-3 custom-file-small">
                            <label for="exampleInputText01" class="h5">Upload Profile Picture</label>
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="inputGroupFile02">
                                <label class="custom-file-label" for="inputGroupFile02">Choose file</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group mb-3">
                            <label for="exampleInputText2" class="h5">Full Name</label>
                            <input type="text" class="form-control" id="exampleInputText2"
                                   placeholder="Enter your full name">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group mb-3">
                            <label for="exampleInputText04" class="h5">Phone Number</label>
                            <input type="text" class="form-control" id="exampleInputText04"
                                   placeholder="Enter phone number">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group mb-3">
                            <label for="exampleInputText006" class="h5">Email</label>
                            <input type="text" class="form-control" id="exampleInputText006"
                                   placeholder="Enter your Email">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group mb-3">
                            <label for="exampleInputText2" class="h5">Type</label>
                            <select name="type" class="selectpicker form-control" data-style="py-0">
                                <option>Type</option>
                                <option>Trainee</option>
                                <option>Employee</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group mb-3">
                            <label for="exampleInputText2" class="h5">Role</label>
                            <select name="type" class="selectpicker form-control" data-style="py-0">
                                <option>Role</option>
                                <option>Designer</option>
                                <option>Developer</option>
                                <option>Manager</option>
                                <option>BDE</option>
                                <option>SEO</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="d-flex flex-wrap align-items-ceter justify-content-center mt-2">
                            <div class="btn btn-primary mr-3" data-dismiss="modal">Save</div>
                            <div class="btn btn-primary" data-dismiss="modal">Cancel</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bd-example-modal-lg" role="dialog" aria-modal="true" id="new-create-modal">
    <div class="modal-dialog  modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header d-block text-center pb-3 border-bttom">
                <h3 class="modal-title" id="exampleModalCenterTitle03">New Task</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group mb-3">
                            <label for="exampleInputText03" class="h5">Task Name</label>
                            <input type="text" class="form-control" id="exampleInputText03"
                                   placeholder="Enter task Name">
                            <a href="#" class="task-edit text-body"><i class="ri-edit-box-line"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group mb-3">
                            <label for="exampleInputText2" class="h5">Assigned to</label>
                            <select name="type" class="selectpicker form-control" data-style="py-0">
                                <option>Memebers</option>
                                <option>Kianna Septimus</option>
                                <option>Jaxson Herwitz</option>
                                <option>Ryan Schleifer</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group mb-3">
                            <label for="exampleInputText2" class="h5">Project Name</label>
                            <select name="type" class="selectpicker form-control" data-style="py-0">
                                <option>Enter your project Name</option>
                                <option>Ui/Ux Design</option>
                                <option>Dashboard Templates</option>
                                <option>Wordpress Themes</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group mb-3">
                            <label for="exampleInputText40" class="h5">Description</label>
                            <textarea class="form-control" id="exampleInputText40" rows="2"
                                      placeholder="Textarea"></textarea>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group mb-3">
                            <label for="exampleInputText8" class="h5">Checklist</label>
                            <input type="text" class="form-control" id="exampleInputText8" placeholder="Add List">
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group mb-0">
                            <label for="exampleInputText01" class="h5">Attachments</label>
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="inputGroupFile01">
                                <label class="custom-file-label" for="inputGroupFile01">Upload media</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="d-flex flex-wrap align-items-ceter justify-content-center mt-4">
                            <div class="btn btn-primary mr-3" data-dismiss="modal">Save</div>
                            <div class="btn btn-primary" data-dismiss="modal">Cancel</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/project-layout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <!-- Alert messages -->
    {% include 'alert-message.html' %}
    
    <!-- Project image -->
    <div class="card car-transparent" style="margin-bottom: -110px;">
        <div class="card-body p-0">
            <div class="profile-image position-relative" style="max-height: 500px; overflow: hidden;">
                <img src="{{project.image.url}}" class="img-fluid rounded w-100" alt="project-image"
                    >
            </div>
        </div>
    </div>

    <!-- Top nav-->
    <div class="px-4">
        <ul class="nav nav-pills mb-3 nav-fill card flex-row {{actived_page}}" id="pills-tab-1" role="tablist" 
                style="background-color: rgba(255,255,255,0.9); border: none;">
            <li class="nav-item" style="flex-basis: 0px;">
                <a class="nav-link {% if actived_page == 'details' %} active {% endif %}" id="pills-home-tab-fill" href="{% url 'project:project' project.id %}" role="tab"
                    aria-controls="pills-home" aria-selected="true">Details</a>
            </li>
            <li class="nav-item" style="flex-basis: 0px;">
                <a class="nav-link {% if actived_page == 'tasks' %} active {% endif %}" id="pills-contact-tab-fill" href="{% url 'tasks' project.id %}" role="tab"
                    aria-controls="pills-contact" aria-selected="false">Tasks</a>
            </li>
            <li class="nav-item" style="flex-basis: 0px;">
                <a class="nav-link {% if actived_page == 'participated employees' %} active {% endif %}" id="pills-profile-tab-fill" href="{% url 'project:get-participants' project.id %}" role="tab"
                    aria-controls="pills-profile" aria-selected="false">Participated Employees</a>
            </li>
        </ul>
        <!-- Top nav end-->
    
        <!-- Main content -->
        {% block content_of_project_layout %}
        {% endblock content_of_project_layout %}
    </div>
</div>


{% endblock content %}